
SET FOREIGN_KEY_CHECKS=0; 

DROP DATABASE IF EXISTS `auditlog`;

DROP DATABASE IF EXISTS `hts`;

DROP DATABASE IF EXISTS `prodlims`;

DROP DATABASE IF EXISTS `diseaseassociations`;

SET FOREIGN_KEY_CHECKS=1;
